FROM adoptopenjdk:11-jdk-hotspot AS build

WORKDIR /app


COPY pom.xml build.gradle ./
RUN --mount=type=cache,target=/root/.m2 \
    --mount=type=cache,target=/root/.gradle \
    mvn package -DskipTests


COPY src ./src
RUN mvn package -DskipTests


FROM openjdk:11-jre-slim
WORKDIR /app
COPY target/server-0.0.1-SNAPSHOT.jar /app
CMD ["java", "-jar", "server-0.0.1-SNAPSHOT.jar"]
