# FROM adoptopenjdk:11-jdk-hotspot AS build

# WORKDIR /app


# COPY pom.xml build.gradle ./
# RUN --mount=type=cache,target=/root/.m2 \
#     --mount=type=cache,target=/root/.gradle \
#     mvn package -DskipTests


# COPY src ./src
# RUN mvn package -DskipTests


# FROM openjdk:11-jre-slim
# WORKDIR /app
# COPY  target/server-0.0.1-SNAPSHOT.jar /app
# EXPOSE 8080
# ENTRYPOINT ["java", "-jar", "server-0.0.1-SNAPSHOT.jar"]



FROM maven:3-amazoncorretto-17 AS build
COPY . .
RUN mvn package -DskipTests

#
# Package stage
#
FROM openjdk:17
COPY --from=build target/server-0.0.1-SNAPSHOT.jar demo.jar
# ENV PORT=8080
EXPOSE 8080
ENTRYPOINT ["java","-jar","demo.jar"]